apps:
default:
  name: App
  domain: localhost
  database:
    client: sqlite3
    connection:
      filename: tmp/db.sqlite
  redis: {}
  passport: {}
  session:
    store: knex
    resave: true
    saveUninitialized: true
etcd:
  enabled: false
  hostname: 127.0.0.1
  port: 4001
prometheus:
  host: 127.0.0.1
  port: 8080
  path: /metrics
mock: false
server:
  host: 0.0.0.0
  port: 80
sslServer:
  host: 0.0.0.0
  port: 443
rules: []
